### ISSUE TITLE
Battle for Middle Earth

### ISSUE THREAD

**Issue by AlexN64gamer** [datajake1999/EAXReverb_VST#1]
Hello developers, sorry to post this here, Im just a noob with this and need some help, Ive installed the lastest release, but when I open the game (BFME 1 and 2) and click on EAX3 in the settings, it keeps telling "your sound card is not EAX compatible" I have a Realtek HD audio, do I need to do something more? thanks in advance

**Comment by datajake1999** [comment]
This project isn't an EAX emulator for games. This project is an audio effect that can be used with a digital audio workstation to add EAX style reverb to a track.
If you are looking for a software based EAX emulator for games that support EAX, you should check out DSOAL and OpenAL Soft.
